name: Upload Model to Azure Blob

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    env:
      AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt azure-storage-blob

    - name: Upload model to Azure Blob
      run: python model_to_blob.py --container models --version latest
